export default function EmbeddedDocs() {
  const docsUrl = `${window.location.protocol}//${window.location.host}/documentation/`

  // Same-origin documentation served by the SignalK server itself.
  // The sandbox requires both allow-scripts (for doc navigation) and allow-same-origin
  // (for accessing server resources). This is safe because:
  // 1. The content is served from the same origin as the admin UI
  // 2. The docs are generated by the SignalK server, not user-supplied
  // 3. This is an internal admin tool, not a public-facing application

  return (
    <iframe
      src={docsUrl}
      style={{
        width: '100%',
        height: 'calc(100vh - 55px)',
        border: 'none'
      }}
      title="Signal K Documentation"
      // eslint-disable-next-line @eslint-react/dom/no-unsafe-iframe-sandbox -- trusted same-origin server docs
      sandbox="allow-scripts allow-same-origin"
    />
  )
}
