#!/usr/bin/env node

if(typeof process.send !== 'function') {
	return process.exit();
}

setTimeout(function() {
	process.send({
		messageType: 'identity', // in order to find out if the message contains actual data or the Provider's identity
		payload: {
			name: 'gps', // name of Provider
			version: '0.0.1', // version of Provider
			author: 'Fabian Tollenaar', // author of Provider
			provides: 'Location data', // description of what the Provider provides
			capabilities: ['gps'], // capabilities/tags
			protocol: 'kSignal', // protocol of the actual data. Should be kSignal
			
			device: { // device information
				protocol: 'nmea0183', // original protocol
				type: 'antenna', // device type
				location: 'rear sea railing', // device location
				manufacturer: 'NavTec', // device manufacturer
				product: 'ABC123', // product identifier
				serial: '0987hkjdal29q485' // serial number
			}
		}
	});
}, 1500);

setTimeout(function() {
	setInterval(function() {
		process.send({
			messageType: 'data', 
			payload: {
				longitude: 0.0,
				latitude: 0.0,
				accuracy: 0.0,
				satellites: 0
			}
		});
	}, 1000);
}, 1500);