#!/usr/bin/env node

/*
 * 
 * saildata-server: An implementation of a Signal K server for boats.
 * Copyright (C) 2014  Fabian Tollenaar <fabian@starting-point.nl>

 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 */

 
if(typeof process.send !== 'function') {
	return process.exit();
}

setTimeout(function() {
	process.send({
		messageType: 'identity', // in order to find out if the message contains actual data or the Provider's identity
		payload: {
			name: 'gps', // name of Provider
			version: '0.0.1', // version of Provider
			author: 'Fabian Tollenaar', // author of Provider
			provides: 'Location data', // description of what the Provider provides
			capabilities: ['gps'], // capabilities/tags
			protocol: 'kSignal', // protocol of the actual data. Should be kSignal
			
			device: { // device information
				protocol: 'nmea0183', // original protocol
				type: 'antenna', // device type
				location: 'rear sea railing', // device location
				manufacturer: 'NavTec', // device manufacturer
				product: 'ABC123', // product identifier
				serial: '0987hkjdal29q485' // serial number
			}
		}
	});
}, 1500);

setTimeout(function() {
	setInterval(function() {
		process.send({
			messageType: 'data', 
			payload: {
				longitude: 0.0,
				latitude: 0.0,
				accuracy: 0.0,
				satellites: 0
			}
		});
	}, 1000);
}, 1500);