#docker buildx build --platform linux/amd64 -f  Dockerfile_heroku_api_demo -t registry.heroku.com/signalk-course-resources-api/web .
#docker push registry.heroku.com/signalk-course-resources-api/web 
#heroku container:release web -a signalk-course-resources-api
FROM signalk/signalk-server:resources_course_api

WORKDIR /home/node/signalk
USER root
COPY startup_heroku_demo.sh startup.sh
RUN chmod +x startup.sh
USER node
