FROM signalk/signalk-server-base:latest

ADD patch patch

RUN npm i -g /patch/signalk-server-*.tgz \
  && ln -s /usr/lib/node_modules/signalk-server /home/node/signalk

WORKDIR /home/node/signalk
RUN npm i /patch/signalk-server-admin-ui-*.tgz --save \
  && npm i /patch/signalk-server-api-*.tgz --save \
  && npm i /patch/signalk-streams-*.tgz --save

COPY --chown=node docker/startup.sh startup.sh
RUN chmod +x startup.sh

USER node
RUN mkdir -p /home/node/.signalk

EXPOSE 3000
ENV IS_IN_DOCKER true
WORKDIR /home/node/.signalk
ENTRYPOINT /home/node/signalk/startup.sh
