FROM ubuntu:26.04
ARG NODE
ENV DEBIAN_FRONTEND=noninteractive

RUN userdel -r ubuntu \
  && groupadd --gid 1000 node \
  && useradd --uid 1000 --gid node --shell /bin/bash --create-home node

RUN groupadd -r docker -g 991 \
  && groupadd -r i2c -g 990 \
  && groupadd -r spi -g 989 \
  && apt-get update \
  && apt-get -y install --no-install-recommends git \
  python3 python3-venv python3-pip build-essential \
  sysstat procps nano curl libcap2-bin sudo bluez \
  && usermod -a -G dialout,i2c,spi,docker node \
  && chmod u+s /usr/bin/date

RUN curl -fsSL https://deb.nodesource.com/setup_$NODE | bash - \
  && apt-get -y install --no-install-recommends nodejs \
  && npm config rm proxy \
  && npm config rm https-proxy \
  && npm config set fetch-retries 5 \
  && npm config set fetch-retry-mintimeout 60000 \
  && npm config set fetch-retry-maxtimeout 120000 \
  && npm cache clean -f \
  && npm install npm@latest -g \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
