ARG NODE
FROM node:${NODE}-alpine

RUN deluser node 2>/dev/null || true && \
    delgroup node 2>/dev/null || true

RUN apk add --no-cache \
    sudo git bash \
    python3 py3-virtualenv py3-pip build-base \
    procps-ng nano curl libcap-setcap bluez \
 && addgroup -g 991 -S docker \
 && addgroup -g 990 -S i2c \
 && addgroup -g 989 -S spi

RUN npm config rm proxy \
 && npm config rm https-proxy \
 && npm config set fetch-retries 5 \
 && npm config set fetch-retry-mintimeout 60000 \
 && npm config set fetch-retry-maxtimeout 120000 \
 && npm cache clean -f \
 && rm -rf /tmp/* /var/tmp/*

RUN addgroup -g 1000 node \
 && adduser -u 1000 -G node -s /bin/sh -D node \
 && addgroup node dialout \
 && addgroup node i2c \
 && addgroup node spi \
 && addgroup node docker \
 && echo 'node ALL=(ALL) NOPASSWD:/bin/date' >> /etc/sudoers

WORKDIR /home/node
USER node
