/**
 * Anchor Watch - C# WASM Plugin for Signal K
 *
 * This implementation uses WIT bindings generated by componentize-dotnet.
 * The plugin interface is defined in wit/signalk-plugin.wit
 */

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;
using SignalkPluginWorld.wit.imports.signalk.plugin.v1_0_0;

namespace SignalkPluginWorld.wit.exports.signalk.plugin.v1_0_0;

/// <summary>
/// Implementation of the Signal K plugin interface defined in WIT
/// </summary>
public class PluginImpl : IPlugin
{
    private static AnchorState anchorState = new AnchorState();
    private static bool debugEnabled = false;

    private static void LogDebug(string message)
    {
        if (debugEnabled)
        {
            SignalkApiInterop.SkDebug($"[anchor-watch-dotnet] {message}");
        }
    }

    /// <summary>
    /// Returns the unique plugin identifier
    /// </summary>
    public static string PluginId()
    {
        return "anchor-watch-dotnet";
    }

    /// <summary>
    /// Returns the human-readable plugin name
    /// </summary>
    public static string PluginName()
    {
        return "Anchor Watch (.NET)";
    }

    /// <summary>
    /// Returns the JSON schema for plugin configuration
    /// </summary>
    public static string PluginSchema()
    {
        return @"{
  ""type"": ""object"",
  ""properties"": {
    ""maxRadius"": {
      ""type"": ""number"",
      ""title"": ""Default Drag Alarm Radius (meters)"",
      ""default"": 50
    },
    ""alarmEnabled"": {
      ""type"": ""boolean"",
      ""title"": ""Enable Alarm"",
      ""default"": false
    },
    ""enableDebug"": {
      ""type"": ""boolean"",
      ""title"": ""Enable Debug Logging"",
      ""default"": false
    }
  }
}";
    }

    /// <summary>
    /// Called when the plugin is started with configuration JSON
    /// </summary>
    public static int PluginStart(string config)
    {
        try
        {
            // Parse configuration
            try
            {
                var configObj = JsonSerializer.Deserialize(config, PluginJsonContext.Default.DictionaryStringJsonElement);
                if (configObj != null)
                {
                    if (configObj.ContainsKey("enableDebug"))
                    {
                        debugEnabled = configObj["enableDebug"].GetBoolean();
                    }

                    var configuration = configObj.ContainsKey("configuration")
                        ? JsonSerializer.Deserialize(configObj["configuration"].GetRawText(), PluginJsonContext.Default.DictionaryStringJsonElement)
                        : null;

                    if (configuration != null)
                    {
                        if (configuration.ContainsKey("maxRadius"))
                        {
                            anchorState.MaxRadius = configuration["maxRadius"].GetDouble();
                        }
                        if (configuration.ContainsKey("alarmEnabled"))
                        {
                            anchorState.AlarmEnabled = configuration["alarmEnabled"].GetBoolean();
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                LogDebug($"Configuration parse error: {ex.Message}");
            }

            LogDebug("========================================");
            LogDebug("Anchor Watch plugin starting...");
            LogDebug($"Configuration: {config}");
            LogDebug($"Debug logging: {(debugEnabled ? "ENABLED" : "DISABLED")}");
            LogDebug($"Max radius: {anchorState.MaxRadius}m");
            LogDebug($"Alarm enabled: {anchorState.AlarmEnabled}");

            // Register PUT handlers
            LogDebug("Registering PUT handlers...");

            if (SignalkApiInterop.SkRegisterPutHandler("vessels.self", "navigation.anchor.position") == 1)
            {
                LogDebug("Registered: navigation.anchor.position");
            }

            if (SignalkApiInterop.SkRegisterPutHandler("vessels.self", "navigation.anchor.maxRadius") == 1)
            {
                LogDebug("Registered: navigation.anchor.maxRadius");
            }

            if (SignalkApiInterop.SkRegisterPutHandler("vessels.self", "navigation.anchor.alarmState") == 1)
            {
                LogDebug("Registered: navigation.anchor.alarmState");
            }

            SignalkApiInterop.SkSetStatus("Started - waiting for anchor drop");

            LogDebug("========================================");
            LogDebug("Anchor Watch plugin started successfully!");
            LogDebug("========================================");

            return 0; // Success
        }
        catch (Exception ex)
        {
            SignalkApiInterop.SkSetError($"Start failed: {ex.Message}");
            return 1; // Error
        }
    }

    /// <summary>
    /// Called when the plugin is stopped
    /// </summary>
    public static int PluginStop()
    {
        LogDebug("Anchor Watch plugin stopping...");
        SignalkApiInterop.SkSetStatus("Stopped");
        return 0;
    }
}

// Data models
public class Position
{
    [JsonPropertyName("latitude")]
    public double Latitude { get; set; }

    [JsonPropertyName("longitude")]
    public double Longitude { get; set; }
}

public class AnchorState
{
    [JsonPropertyName("position")]
    public Position? Position { get; set; }

    [JsonPropertyName("maxRadius")]
    public double MaxRadius { get; set; } = 50.0;

    [JsonPropertyName("alarmEnabled")]
    public bool AlarmEnabled { get; set; } = false;
}

public class PutRequest
{
    [JsonPropertyName("context")]
    public string Context { get; set; } = "";

    [JsonPropertyName("path")]
    public string Path { get; set; } = "";

    [JsonPropertyName("value")]
    public JsonElement Value { get; set; }
}

public class PutResponse
{
    [JsonPropertyName("state")]
    public string State { get; set; } = "COMPLETED";

    [JsonPropertyName("statusCode")]
    public int StatusCode { get; set; } = 200;

    [JsonPropertyName("message")]
    public string? Message { get; set; }
}

// JSON source generator context for AOT/trimming compatibility
[JsonSourceGenerationOptions(WriteIndented = false)]
[JsonSerializable(typeof(Dictionary<string, JsonElement>))]
[JsonSerializable(typeof(Position))]
[JsonSerializable(typeof(AnchorState))]
[JsonSerializable(typeof(PutRequest))]
[JsonSerializable(typeof(PutResponse))]
internal partial class PluginJsonContext : JsonSerializerContext
{
}
