[book]
title="Signal K Server Documentation"
description = "A Guide for users and developers."
authors = []
language = "en"
multilingual = false
src = "src"

[build]
build-dir = "built"
create-missing = false


