name: CI test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - run: pnpm install
      - run: pnpm run build:all

      - name: resources-provider-plugin
        working-directory: ./packages/resources-provider-plugin
        run: |
          pnpm run test

      - run: pnpm test
        env:
          CI: true
